"""add reply_check_attempts to messages

Revision ID: 577eec80d419
Revises: 29d4286a9127
Create Date: 2026-05-24 09:47:04.136261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577eec80d419'
down_revision: Union[str, Sequence[str], None] = '29d4286a9127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_check_attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reply_check_attempts')
    # ### end Alembic commands ###
