"""update_gmail_credentials_unique_user

Revision ID: be5f2a161cf1
Revises: 4fb66c8f2b84
Create Date: 2026-05-25 15:23:37.556373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5f2a161cf1'
down_revision: Union[str, Sequence[str], None] = '4fb66c8f2b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.add_column('gmail_credentials', sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index('ix_gmail_credentials_user_id', table_name='gmail_credentials')
    op.create_index(op.f('ix_gmail_credentials_user_id'), 'gmail_credentials', ['user_id'], unique=True)
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.drop_index(op.f('ix_gmail_credentials_user_id'), table_name='gmail_credentials')
    op.create_index('ix_gmail_credentials_user_id', 'gmail_credentials', ['user_id'], unique=False)
    op.drop_column('gmail_credentials', 'connected_at')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    # ### end Alembic commands ###
